
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Dilber Taştan
 */
public class menu2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form menu1
     */
    public menu2() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0) );
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn2ingilizce = new javax.swing.JButton();
        btn2japonca = new javax.swing.JButton();
        btn2hintçe = new javax.swing.JButton();
        btn2korece = new javax.swing.JButton();
        btn2arapça = new javax.swing.JButton();
        btn2italyanca = new javax.swing.JButton();
        btn2fransızca = new javax.swing.JButton();
        btn2alman = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(900, 510));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(900, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204,210));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204,210));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Hangi dilin kelime grubuna girmek istersiniz?");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 540, 53));

        jPanel4.setBackground(new java.awt.Color(204,204,204,210));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/united-kingdom (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204,204,204,210));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japan (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204,204,204,210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/france (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204,210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/germany (3) (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jPanel7.setBackground(new java.awt.Color(204,204,204,210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flag (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jPanel8.setBackground(new java.awt.Color(204,204,204,210));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/south-korea (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jPanel9.setBackground(new java.awt.Color(204,204,204,210));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saudi-arabia (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jPanel10.setBackground(new java.awt.Color(204,204,204,210));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/italy (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));

        btn2ingilizce.setBackground(new java.awt.Color(255, 204, 204));
        btn2ingilizce.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn2ingilizce.setText("İngilizce");
        btn2ingilizce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ingilizceActionPerformed(evt);
            }
        });
        jPanel2.add(btn2ingilizce, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        btn2japonca.setBackground(new java.awt.Color(255, 204, 204));
        btn2japonca.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn2japonca.setText("Japonca");
        btn2japonca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2japoncaActionPerformed(evt);
            }
        });
        jPanel2.add(btn2japonca, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));

        btn2hintçe.setBackground(new java.awt.Color(255, 204, 204));
        btn2hintçe.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn2hintçe.setText("Hintçe");
        btn2hintçe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2hintçeActionPerformed(evt);
            }
        });
        jPanel2.add(btn2hintçe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        btn2korece.setBackground(new java.awt.Color(255, 204, 204));
        btn2korece.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn2korece.setText("Korece");
        btn2korece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2koreceActionPerformed(evt);
            }
        });
        jPanel2.add(btn2korece, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        btn2arapça.setBackground(new java.awt.Color(255, 204, 204));
        btn2arapça.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn2arapça.setText("Arapça");
        btn2arapça.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2arapçaActionPerformed(evt);
            }
        });
        jPanel2.add(btn2arapça, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        btn2italyanca.setBackground(new java.awt.Color(255, 204, 204));
        btn2italyanca.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn2italyanca.setText("İtalyanca");
        btn2italyanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2italyancaActionPerformed(evt);
            }
        });
        jPanel2.add(btn2italyanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        btn2fransızca.setBackground(new java.awt.Color(255, 204, 204));
        btn2fransızca.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn2fransızca.setText("Fransızca");
        btn2fransızca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2fransızcaActionPerformed(evt);
            }
        });
        jPanel2.add(btn2fransızca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        btn2alman.setBackground(new java.awt.Color(255, 204, 204));
        btn2alman.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn2alman.setText("Almanca");
        btn2alman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2almanActionPerformed(evt);
            }
        });
        jPanel2.add(btn2alman, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel11.setText("EN ÇOK KULLANILAN KELİMELER");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 383, 53));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 910, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arkaplan (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 910, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ingilizceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ingilizceActionPerformed
        kelimeingilizce kelimeingilizce =new kelimeingilizce();
        kelimeingilizce.setVisible(true);

    }//GEN-LAST:event_btn2ingilizceActionPerformed

    private void btn2japoncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2japoncaActionPerformed
       kelimejaponca kelimejaponca=new kelimejaponca();
       kelimejaponca.setVisible(true);

    }//GEN-LAST:event_btn2japoncaActionPerformed

    private void btn2hintçeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2hintçeActionPerformed
      kelimehintçe kelimehintçe =new kelimehintçe();
      kelimehintçe.setVisible(true);

    }//GEN-LAST:event_btn2hintçeActionPerformed

    private void btn2koreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2koreceActionPerformed
        kelimekorece kelimekorece =new kelimekorece();
        kelimekorece.setVisible(true);

    }//GEN-LAST:event_btn2koreceActionPerformed

    private void btn2arapçaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2arapçaActionPerformed
        kelimearapça kelimearapça =new kelimearapça();
        kelimearapça.setVisible(true);

    }//GEN-LAST:event_btn2arapçaActionPerformed

    private void btn2italyancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2italyancaActionPerformed
        kelimeitalyanca kelimeitalyanca =new kelimeitalyanca();
        kelimeitalyanca.setVisible(true);

    }//GEN-LAST:event_btn2italyancaActionPerformed

    private void btn2fransızcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2fransızcaActionPerformed
        kelimefransızca kelimefransızca =new kelimefransızca();
        kelimefransızca.setVisible(true);
    }//GEN-LAST:event_btn2fransızcaActionPerformed

    private void btn2almanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2almanActionPerformed
         kelimealmanca kelimealmanca =new kelimealmanca();
         kelimealmanca.setVisible(true);
    }//GEN-LAST:event_btn2almanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2alman;
    private javax.swing.JButton btn2arapça;
    private javax.swing.JButton btn2fransızca;
    private javax.swing.JButton btn2hintçe;
    private javax.swing.JButton btn2ingilizce;
    private javax.swing.JButton btn2italyanca;
    private javax.swing.JButton btn2japonca;
    private javax.swing.JButton btn2korece;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
