
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Dilber Taştan
 */
public class menu1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form menu1
     */
    public menu1() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0) );
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btningilizce = new javax.swing.JButton();
        btnjaponca = new javax.swing.JButton();
        btnhintçe = new javax.swing.JButton();
        btnkorece = new javax.swing.JButton();
        btnarapça = new javax.swing.JButton();
        btnitalyanca = new javax.swing.JButton();
        btnfransızca = new javax.swing.JButton();
        btnalman = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1070, 600));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(900, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204,210));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Hangi dilin sohbetine girmek istersiniz?");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 470, 53));

        jPanel4.setBackground(new java.awt.Color(204,204,204,210));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/united-kingdom (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204,204,204,210));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/japan (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204,204,204,210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/france (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204,210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/germany (3) (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jPanel6.setBackground(new java.awt.Color(204,204,204,210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flag (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jPanel7.setBackground(new java.awt.Color(204,204,204,210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/south-korea (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jPanel8.setBackground(new java.awt.Color(204,204,204,210));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saudi-arabia (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jPanel9.setBackground(new java.awt.Color(204,204,204,210));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/italy (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, -1));

        btningilizce.setBackground(new java.awt.Color(255, 204, 204));
        btningilizce.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btningilizce.setText("İngilizce");
        btningilizce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningilizceActionPerformed(evt);
            }
        });
        jPanel2.add(btningilizce, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        btnjaponca.setBackground(new java.awt.Color(255, 204, 204));
        btnjaponca.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnjaponca.setText("Japonca");
        btnjaponca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjaponcaActionPerformed(evt);
            }
        });
        jPanel2.add(btnjaponca, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));

        btnhintçe.setBackground(new java.awt.Color(255, 204, 204));
        btnhintçe.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnhintçe.setText("Hintçe");
        btnhintçe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhintçeActionPerformed(evt);
            }
        });
        jPanel2.add(btnhintçe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        btnkorece.setBackground(new java.awt.Color(255, 204, 204));
        btnkorece.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnkorece.setText("Korece");
        btnkorece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkoreceActionPerformed(evt);
            }
        });
        jPanel2.add(btnkorece, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        btnarapça.setBackground(new java.awt.Color(255, 204, 204));
        btnarapça.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnarapça.setText("Arapça");
        btnarapça.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarapçaActionPerformed(evt);
            }
        });
        jPanel2.add(btnarapça, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        btnitalyanca.setBackground(new java.awt.Color(255, 204, 204));
        btnitalyanca.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnitalyanca.setText("İtalyanca");
        btnitalyanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitalyancaActionPerformed(evt);
            }
        });
        jPanel2.add(btnitalyanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, -1, -1));

        btnfransızca.setBackground(new java.awt.Color(255, 204, 204));
        btnfransızca.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnfransızca.setText("Fransızca");
        btnfransızca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfransızcaActionPerformed(evt);
            }
        });
        jPanel2.add(btnfransızca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        btnalman.setBackground(new java.awt.Color(255, 204, 204));
        btnalman.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnalman.setText("Almanca");
        btnalman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalmanActionPerformed(evt);
            }
        });
        jPanel2.add(btnalman, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1070, 540));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arkaplan (1).jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 910, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfransızcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfransızcaActionPerformed
           fransızca fransızca =new fransızca();
           fransızca.setVisible(true);
           
    }//GEN-LAST:event_btnfransızcaActionPerformed

    private void btningilizceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningilizceActionPerformed
         ingilizce ingilizce =new ingilizce();
         ingilizce.setVisible(true);
           
    }//GEN-LAST:event_btningilizceActionPerformed

    private void btnjaponcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjaponcaActionPerformed
        japonca japonca =new japonca();
           japonca.setVisible(true);
           
    }//GEN-LAST:event_btnjaponcaActionPerformed

    private void btnhintçeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhintçeActionPerformed
        hintçe hintçe=new hintçe();
           hintçe.setVisible(true);
           
    }//GEN-LAST:event_btnhintçeActionPerformed

    private void btnkoreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkoreceActionPerformed
       korece korece =new korece();
           korece.setVisible(true);
         
           
    }//GEN-LAST:event_btnkoreceActionPerformed

    private void btnarapçaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarapçaActionPerformed
        arapça arapça =new arapça();
           arapça.setVisible(true);
          
    }//GEN-LAST:event_btnarapçaActionPerformed

    private void btnitalyancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitalyancaActionPerformed
        italyanca italyanca =new italyanca();
           italyanca.setVisible(true);
           
    }//GEN-LAST:event_btnitalyancaActionPerformed

    private void btnalmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalmanActionPerformed
       almanca almanca =new almanca();
           almanca.setVisible(true);
    }//GEN-LAST:event_btnalmanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalman;
    private javax.swing.JButton btnarapça;
    private javax.swing.JButton btnfransızca;
    private javax.swing.JButton btnhintçe;
    private javax.swing.JButton btningilizce;
    private javax.swing.JButton btnitalyanca;
    private javax.swing.JButton btnjaponca;
    private javax.swing.JButton btnkorece;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
